### PR TITLE
don't pad unless needed

### PR DESCRIPTION
**Pull request by dryajov**

### CODE REVIEW

**Comment by markspanbroek** [comment]
If I understand this correctly, then you don't want to pad when the number of bytes is a multiple of 31.
Wouldn't this lead to a collision between these two byte strings?
1. 0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA01 (30 times AA plus 01)
2. 0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA (30 times AA)

**Comment by dryajov** [comment]
> If I understand this correctly, then you don't want to pad when the number of bytes is a multiple of 31. Wouldn't this lead to a collision between these two byte strings?
> 
> 1. 0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA01 (30 times AA plus 01)
> 2. 0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA (30 times AA)

Doesn't the marker prevent that?

**Comment by dryajov** [comment]
The problem is that we're adding an extra `00....01` element if the input is a multiple of 31, so if I pass in 310 bytes, I end up with 320, one of them all zeros and one marker.

**Comment by dryajov** [comment]
OK, so this is definitely more subtle than initially thought and needs to be captured somewhere, so here goes:

First, both padding scheme are vulnerable, as in both cases, this sequences can be naturally occurring in the byte stream and unless the size of the original stream is unknown, it's impossible to know if two field elements map to the same enclosing byte string.

Second, the fact that `elements` returns something other than `ceil(nbytes/31)`  is unexpected and should probably be avoided.

The common way to address this seems to be including the amount of padded bytes in the enclosing block to distinguish it from naturally occurring sequences. 

Some more info can be found here - [Byte_padding](https://en.wikipedia.org/wiki/Padding_(cryptography)#Byte_padding)

Right now, I'm leaning towards the [Merkle-Damgrad compliant padding](https://en.wikipedia.org/wiki/Merkle%E2%80%93Damg%C3%A5rd_construction#MD-compliant_padding), which consists in adding a marker byte just as we're doing, followed by a number of `0` padding bytes, and the amount of padding bytes in the final byte.

**Comment by markspanbroek** [comment]
I remember going over the options for padding when we were discussing @bkomuves's [merkle tree design document](https://github.com/codex-storage/codex-research/pull/189). We then decided to go for the [last option in this paragraph](https://github.com/codex-storage/codex-research/blob/415bb6db8c588029ba6651896c8a010682c32e12/design/Merkle.md#making-deserialize-injective), so that's what I implemented. It should protect against the sort of collisions that I mentioned above, at the expense of adding an extra field element when the input is an exact multiple of 31 bytes. I don't think that we can avoid that.

**Comment by dryajov** [comment]
I think we're talking about slightly different things here, and this is part of the problem/confusion. I'm talking about mapping a group of bytes from `1..31` to a single field element, you're talking about mapping a sequence of bytes to (potentially) several field elements. Both are needed. 

For one, I'm not entirely convinced that `elements` should be this coupled with the merkle construct, after all you can (and should be able to) use the `sponge` and `perm` functions standalone, without the use of the merkle tree. This padding should then be handled as part of the merkle tree itself and `elements` (or something similar) should be left generic enough to be usable standalone.

Second, I'm not entirely convinced that this is the only and best way of dealing with this cases, the other options presented in that link seems to be more straightforward and definitely less awkward to deal with?

@bkomuves I'd like to hear your thoughts.

**Comment by bkomuves** [comment]
We need to pad even if the input is a multiple of 31 bytes, because of the case Mark described. There are many ways to solve this, one is _always_ adding say a 0x01, and then add 0x00 bytes until it becomes a multiple of 31 (this strategy is usually abbreviated `10*`, abusing regexp notation). This works because from such a padded bytestring you can always recover the original length. A different way is prepend or append the length. SHA2 actually combines these. SHA3/Keccak uses `10*1` but with bits, not bytes (SHA2 also works with bits, not bytes).

It doesn't really matter exactly what we do, but doing a simple `10*` makes streaming easier than using the length, so we agreed to standardize on this one. We also use the same for sponge (there with field elements instead of bytes), because Poseidon paper also uses this, but since our permutation is very short, this padding is not so visible. 

You could also use this for padding the bottom layer of a Merkle tree to a power of two, but that would be very inefficient so instead we do the more complicated strategy for constructing Merkle trees we agreed upon.

**Comment by bkomuves** [comment]
btw any change which actually changes the output for any particular input should be probably discussed before trying to implement it. It is possible that there are bugs, both theoretical and implementation (the latter less like because we have several independent implementations), but apart from bugs, things are usually the way they are for reasons.

**Comment by dryajov** [comment]
> btw any change which actually changes the output for any particular input should be probably discussed before trying to implement it. It is possible that there are bugs, both theoretical and implementation (the latter less like because we have several independent implementations), but apart from bugs, things are usually the way they are for reasons.

ugh, the fact that there are independent implementation doesn't mean that they are correct and the changes made here are minimal.

besides, changes should and will be proposed without a "committee" in between, thats what PRs are for.

**Comment by bkomuves** [comment]
Having independent implementations give you some level of confidence that the implementation is conforming a specification, of course not that the specification itself is making any sense. However in this particular case I believe the specification was correct, in the sense that you should definitely pad even if the input length was divisible by 31.

Cryptographic primitives is not something you just change on a whim after they are settled, for several reasons. So discussing changes is certainly something I believe is a good idea. I was not even aware of your proposal before I was tagged later in the discussion.

**Comment by dryajov** [comment]
> However in this particular case I believe the specification was correct, in the sense that you should definitely pad even if the input length was divisible by 31.

Obviously there are subtleties to it that are easy to miss, this is why the change was proposed. Regardless, there this are good things to note in the comments, as it will throw many people off when debugging, as it did with me.

> Cryptographic primitives is not something you just change on a whim after they are settled, for several reasons. So discussing changes is certainly something I believe is a good idea. I was not even aware of your proposal before I was tagged later in the discussion.

A PR is a great way of having this discussion, which is what we're doing now :)

**Comment by bkomuves** [comment]
OK, I thought a bit on how the phrase this padding issue the best, so I try to write this down below. After that, I suggest to close this without merging. 

> A PR is a great way of having this discussion, which is what we're doing now :)

Ok, but next time please add me to the PR as a reviewer or tag me or something...

Anyway:

What is padding? It's a mapping from a set of sequences into a subset. In this case it's a sequence of bytes, and we map into the subset of sequences whose length is divisible by 31.

Why do we want padding? Because we want to apply an algorithm (in this case a hash function) to arbitrary sequences, but the algorithm can only handle a subset of all sequences.

What properties do we want from padding? Well that depends on what what properties we want from the resulting algorithm. In this case we do hashing, so we definitely want to avoid collisions. This means that our padding should never map two different input sequences into the same padded sequence (because that would create a collision). In math, we call such functions "injective".

How do you show that a function is NOT injective? Simple, just provide two different inputs which map into the same output. Mark did that above for the "optimized" padding strategy.

How do you prove that a function is injective? You provide an inverse function, which takes a padded sequences and outputs the original one. This is very easy do to for `10*` padding strategy: First remove all the trailing zero bytes. After, that the last byte must by `0x01`, because that's how our padding function is constructed. Now remove that 0x01 byte too. What you got is clearly the original sequence. 

So we proved that the `10*` strategy satisfies the injectivity. It also satisfies that the output length is divisible by 31. This is all we needed.

**Comment by dryajov** [comment]
> Ok, but next time please add me to the PR as a reviewer or tag me or something...

You can easily get all the notifications for a repo (you **should** for this repo) by setting to `Watch` to `All Activity`, here is a screenshot:

Screenshot 2023-12-20 at 10 18 37 AM

----------------------------

> So we proved that the 10* strategy satisfies the injectivity. It also satisfies that the output length is divisible by 31. This is all we needed.

This PR doesn't remove padding, it modifies it (albeit incorrectly), and the links I provided in https://github.com/codex-storage/nim-poseidon2/pull/17#issuecomment-1861502851, talk about common cryptographic padding strategies. The `10*` approach, doesn't seem to be a widely used cryptographic padding pattern - it is used in `ISO/IEC 7816-4` as per the [Wikipedia padding article](https://en.wikipedia.org/wiki/Padding_(cryptography)#ISO/IEC_7816-4), but this isn't considered a cryptographic protocol. 

To quote:

> The zero padding scheme has not been standardized for encryption

and 

> Zero padding may not be reversible if the original file ends with one or more zero bytes, making it impossible to distinguish between plaintext data bytes and padding bytes. It may be used when the length of the message can be derived [out-of-band](https://en.wikipedia.org/wiki/Out-of-band_data). It is often applied to binary encoded[[clarification needed](https://en.wikipedia.org/wiki/Wikipedia:Please_clarify)] [strings](https://en.wikipedia.org/wiki/String_(computer_science)) ([null-terminated string](https://en.wikipedia.org/wiki/Null-terminated_string)) as the [null character](https://en.wikipedia.org/wiki/Null_character) can usually be stripped off as [whitespace](https://en.wikipedia.org/wiki/Whitespace_character).

The more accepted methods of going around this seem to be the ones used in [ANSI X9.23](https://en.wikipedia.org/wiki/Padding_(cryptography)#ANSI_X9.23),   [ISO_10126](https://en.wikipedia.org/wiki/Padding_(cryptography)#ISO_10126) and [5 and 7 PKCS](https://en.wikipedia.org/wiki/Padding_(cryptography)#PKCS#5_and_PKCS#7).

Yes, I realize now that this is addressed by _always_ adding an extra element to the sequence, this guarantees that the padding is injective, but at the cost of one extra field element in the case of sequences of multiple of `31`.

Now, the question is, can we avoid this extra element in our specific case and more importantly, does it matter?  

The two reasons I think it might matter is 1) it's a bit un-intuitive to get an extra field element when using the `elements` iterator, but perhaps this isn't that important, since it's more of a private api and 2), some potential minor overhead of having to process an extra element - anything else we can think of where this might break?

**Comment by bkomuves** [comment]
`10*` is NOT the zero padding. The zero padding (one of `0*` or `0+` with the regexp notation) would be indeed unsafe. However I just proved above, mathematically, why the `10*` strategy is safe for usage. 

> The 10* approach doesn't seem to be a widely used cryptographic padding pattern

It doesn't matter which padding scheme we use as long as it's injective. SHA3 uses `10*1` (with bits), so almost the same; using that on bytes however would mean that even 30-byte sequences would get an extra field element. We could use `10*1` on bits, exactly the same as SHA3 if that makes you happier, so that we can close this discussion already :) It really doesn't matter though. 

> but at the cost of one extra field element in the case of sequences of multiple of 31.
> Now, the question is, can we avoid this extra element in our specific case and more importantly, does it matter?

There is no safe padding strategy which doesn't occasionally add such extra "blocks" (which will then turn into an extra field element in our case). Why is this? Suppose inputs of length `31*k` are not padded (like in your PR). However inputs of all other size must be padded to have length divisible by 31 (that's the only reason we want padding at all!). So you won't be able to distinguish between something which was smaller and padded to `31*k` and the resulting padded bytestring considered as an input itself. 

So no, we cannot avoid this, and no, it doesn't matter. It's can cause a tiny minor slowdown in some causes, however you would give up safety which is much more important. By the way in our application we use this for 2048 byte cells, and 2048 is not divisible by 31, so this "optimization" wouldn't help anyway.

By the way, you already accepted such an inefficiency by using SHA256 for constructing binary Merkle trees. SHA256 consumes data in 512-bit (64-byte) blocks. A padding is always added (it consists of: `10*` followed by the original length of the input encoded as a 64-bit integer), so when you calculate `H(x|y)` at a node, because `x` and `y` are 32 bytes each, and then you add padding, internally you process two blocks (1024 bits or 128 bytes). So that's a 2x slowdown compared to using an _unpadded_ version of SHA256 (which would be in fact safe for this particular use case, because the inputs are always the same size, 64 bytes).

> The two reasons I think it might matter is 1) it's a bit un-intuitive to get an extra field element when using the elements iterator

Just rename `elements` to something else. You cannot avoid this.

**Comment by dryajov** [comment]
> We could use 10*1 on bits, exactly the same as SHA3 if that makes you happier, so that we can close this discussion already :) It really doesn't matter though.

Lol, I don't have a preference either, I'm just making sure we've covered all the bases. This works and it's good we went over it again.

> By the way, you already accepted such an inefficiency by using SHA256 for constructing binary Merkle trees. SHA256 consumes data in 512-bit (64-byte) blocks.

This is something to re-evaluate at some point, we aren't tied to sha256 in any way and we can switch this (even after shipping) easily. So if you have a suggestion for a better hash (sha3/keccak, blake2, etc...) we can definitely change it, specially in the context of circuits (but, I think most are focused in making sha2/3/keccak faster).

**Comment by bkomuves** [comment]
> This is something to re-evaluate at some point, we aren't tied to sha256 in any way and we can switch this (even after shipping) easily. So if you have a suggestion for a better hash (sha3/keccak, blake2, etc...) we can definitely change it, specially in the context of circuits (but, I think most are focused in making sha2/3/keccak faster).

I actually like SHA256 because it's widely known, accepted as safe, and it's accelerated on modern commodity hardware so CPU hashing is very fast. Blake3 is about as fast unaccelerated as SHA256 is accelerated, however apparently much less secure (it should be secure, but just barely. SHA256 has quite some "safety buffer"). SHA3 would be also a good choice but it's somewhat less efficient at the moment (on both CPU and circuits) and less commonly accelerated (but that latter may change it the future).

Ideally the best would use the same hash for networking and proving, and I would prefer to use SHA256 (Poseidon2 also has questionable safety, and the CPU implementation is much more complex and slow), but we need further research on whether we can do that. Best to be prepared to change hash functions or allow different choices at the same time.

**Comment by dryajov** [comment]
> Ideally the best would use the same hash for networking and proving, and I would prefer to use SHA256 (Poseidon2 also has questionable safety, and the CPU implementation is much more complex and slow), but we need further research on whether we can do that. Best to be prepared to change hash functions or allow different choices at the same time.

Yes, it should be straightforward to change the hashing for both the storage and proving systems.

**Pull request closed without merging**
