### PR TITLE
Streaming API for merkle root calculation

### PR DESCRIPTION
**Pull request by markspanbroek**
Calculates parts of the merkle tree while leafs are being added.
Changes the API to match the Sponge streaming API.

### CODE REVIEW

**Comment by bkomuves** [comment]
I would keep the non-streaming API too, because the implementation is much simpler, and use it to test the streaming API against.

**Comment by markspanbroek** [comment]
What useful tests can we add using the old implementation? The way I see it, the new implementation is already tested against the old, because they pass the same tests. And those tests include the test vectors from the Haskell implementation.

**Comment by bkomuves** [comment]
I always feel better with 1) more tests 2) tests comparing different implementations. This is cheap to do, it doesn't cause significant code bloat (this is a very small amount of code), what's an argument for _not doing it_?

And the streaming implementation is quite impenetrable at first (superficial) sight, so the old implementation is also good as an executable specification.

**Comment by markspanbroek** [comment]
Well, I didn't see any benefits (same tests, but then against reference implementation, instead of test vectors), more code to maintain (even if it's not that much), and possible confusion when reading the code (why are there two implementation of the same thing).

But I'll go with your instincts and do the following:
- move the reference implementation to the tests folder
- add fuzzing test that generates random input data, and checks that both implementations
   generate the same merkle root

**Pull request merged**
